"""ORM model registry for the complete P0.T3 schema."""

from bodrye_bot.db.models.entities import (
    Angle,
    Approval,
    AuditEvent,
    BackupRun,
    Claim,
    ContentWorkflow,
    CostEvent,
    DeletionTombstone,
    DigestItem,
    DraftVersion,
    Evidence,
    LibraryItem,
    ProviderRun,
    PublicationJob,
    ReviewDecision,
    Source,
    SourceDocument,
    SourceHealthEvent,
    SourcePayloadCache,
    StyleEditObservation,
    StyleExample,
    StyleProfile,
    StyleRule,
)

__all__ = [
    "Angle",
    "Approval",
    "AuditEvent",
    "BackupRun",
    "Claim",
    "ContentWorkflow",
    "CostEvent",
    "DeletionTombstone",
    "DigestItem",
    "DraftVersion",
    "Evidence",
    "LibraryItem",
    "ProviderRun",
    "PublicationJob",
    "ReviewDecision",
    "Source",
    "SourceDocument",
    "SourceHealthEvent",
    "SourcePayloadCache",
    "StyleExample",
    "StyleEditObservation",
    "StyleProfile",
    "StyleRule",
]
